// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp3VTnBrgtUh6_SFoEUoUdfy7pBqRI7sU',
    appId: '1:921090486288:web:3c80cd0084e9c9a5d09a95',
    messagingSenderId: '921090486288',
    projectId: 'chatting-app-59400',
    authDomain: 'chatting-app-59400.firebaseapp.com',
    storageBucket: 'chatting-app-59400.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtA6OlVA6-gZacr8ZpTW-1juI2ecOADWk',
    appId: '1:921090486288:android:e88cd839decc2339d09a95',
    messagingSenderId: '921090486288',
    projectId: 'chatting-app-59400',
    storageBucket: 'chatting-app-59400.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCmAHMqnT5YI9SOcBrruHhKIYZUMkLPiA',
    appId: '1:921090486288:ios:4c8309c5f816c7cdd09a95',
    messagingSenderId: '921090486288',
    projectId: 'chatting-app-59400',
    storageBucket: 'chatting-app-59400.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCmAHMqnT5YI9SOcBrruHhKIYZUMkLPiA',
    appId: '1:921090486288:ios:f3e18d9dbf497338d09a95',
    messagingSenderId: '921090486288',
    projectId: 'chatting-app-59400',
    storageBucket: 'chatting-app-59400.appspot.com',
    iosBundleId: 'com.example.chattingApp.RunnerTests',
  );
}
